[package]
name = "pdb"
version = "0.1.4"
description = "A parser for Microsoft PDB (Program Database) debugging information"
repository = "https://github.com/willglynn/pdb"
authors = ["Will Glynn <will@willglynn.com>"]
readme = "README.md"
license = "MIT OR Apache-2.0"

[dependencies]
fallible-iterator = "0.1.3"
byteorder = "1.0.0"
uuid = "0.5.0"

[dev-dependencies]
# for examples/
getopts = "0.2"

[package.metadata.release]
pre-release-commit-message = "Release {{version}}"
tag-message = "Release {{version}}"
no-dev-version = true
